# Copyright DWJ 2024.
# Distributed under the Boost Software License, Version 1.0.
# https://www.boost.org/LICENSE_1_0.txt

services:
  web:
    image: ghcr.io/${GITHUB_REPO:-repo}:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: $GITHUB_USER
        GITHUB_REPO: $GITHUB_REPO
        GITHUB_TOKEN: $GITHUB_TOKEN
        PUBLIC_URL: $PUBLIC_URL
    ports:
      - "3000:80"
    restart: unless-stopped
    volumes:
      - ./data:/root/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://web:80/"]
      interval: 15s
      timeout: 5s
      retries: 5
